before_script:
    - chmod +x ./testing-setup.sh
    - ./testing-setup.sh

unit_tests:
    script:
        - ./virtualenv/bin/python manage.py test accounts lists
    tags:
        - goats

functional_tests:
    script:
        - xvfb-run ./virtualenv/bin/python manage.py test functional_tests
    tags:
        - goats
